import type { Metadata } from "next";
import { Inter, Quicksand} from "next/font/google";
import {GoogleOAuthProvider} from "@react-oauth/google"
import  { Toaster } from 'react-hot-toast';

import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
const quicksand = Quicksand({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId="398020698451-a1s11tgcjduffell5mc0237v777o4788.apps.googleusercontent.com">
        {children}
        <Toaster />
        </GoogleOAuthProvider>
        </body>
    </html>
  );
} 


